# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=6)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('day', 'Day'), ('date', 'Date')], default='normal', max_length=20)),
                ('created', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('anonymous_allowed', models.BooleanField(default=True)),
                ('public_listening', models.BooleanField(default=False)),
                ('require_login', models.BooleanField(default=False)),
                ('require_invitation', models.BooleanField(default=False)),
                ('show_results', models.CharField(choices=[('summary', 'Summary'), ('complete', 'Complete'), ('never', 'Never'), ('summary after vote', 'Summary after Vote'), ('complete after vote', 'Complete after Vote')], default='complete', max_length=20)),
                ('send_mail', models.BooleanField(default=False)),
                ('one_vote_per_user', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('show_invitations', models.BooleanField(default=True)),
                ('timezone_name', models.CharField(default='Europe/Berlin', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PollWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('anonymous', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField()),
                ('comment', models.TextField()),
                ('assigned_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigning', to=settings.AUTH_USER_MODEL)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Choice')),
                ('value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.ChoiceValue')),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Vote')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='poll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choicevalue',
            name='poll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
    ]
