# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.AlterField(
            model_name='poll',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('universal', 'Universal'), ('datetime', 'Date-Time'), ('date', 'Date')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='poll',
            name='url',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
