# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20160229_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicevalue',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pollwatch',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='pollwatch',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='user',
        ),
    ]
