# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 21:59
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20170309_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
    ]
