# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20160503_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('universal', 'Universal'), ('datetime', 'Date-Time'), ('date', 'Date')], default='universal', max_length=20),
        ),
    ]
