# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0005_auto_20170324_1034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollwatch',
            unique_together=set([('poll', 'user')]),
        ),
    ]
