# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20161102_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='sort_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('poll', 'sort_id')]),
        ),
    ]
