# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20170111_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='sort_id',
            new_name='sort_key',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='assigned_by_id',
            new_name='assigned_by',
        ),
        migrations.RenameField(
            model_name='votechoice',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='votechoice',
            old_name='value_id',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='votechoice',
            old_name='vote_id',
            new_name='vote',
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('poll', 'sort_key')]),
        ),
        migrations.AlterUniqueTogether(
            name='votechoice',
            unique_together=set([('vote', 'choice')]),
        ),
    ]
