# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20170111_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votechoice',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.ChoiceValue'),
        ),
    ]
