# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_merge_20170419_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote_all',
            field=models.BooleanField(default=False),
        ),
    ]
