# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20170219_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
