# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_choicevalue_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicevalue',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('#?[a-fA-F0-9]{6}$', message='Give an HTML color without the #')]),
        ),
    ]
