# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20170224_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='url',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
