# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20170315_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='last_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.Vote'),
        ),
    ]
