# Generated by Django 5.0.6 on 2026-03-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20170315_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
