#!/bin/sh -e
export USER=www-data HOME=/opt/bitpoll
python3 /opt/bitpoll/manage.py migrate
rm -rf /opt/static/*
cp -r /opt/bitpoll/_static/* /opt/static/
if [ -f /opt/config/favicon.ico ]; then
	cp /opt/config/favicon.ico /opt/static/favicon.ico
fi
exec uwsgi /etc/uwsgi/bitpoll.ini
