# Generated by Django 2.0.7 on 2018-07-11 09:20

import bitpoll.caldav.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('caldav', '0001_initial'), ('caldav', '0002_davcalendar_name'), ('caldav', '0003_auto_20180710_1754')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DavCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', bitpoll.caldav.models.EncryptedURLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Calendar', max_length=80)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='davcalendar',
            unique_together={('url', 'user')},
        ),
    ]
