# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_merge_20170419_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitpolluser',
            name='displayname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
