# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:20
from __future__ import unicode_literals

import bitpoll.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_dudeluser_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpolluser',
            name='timezone',
            field=models.CharField(default='Europe/Berlin', max_length=40, validators=[bitpoll.base.validators.validate_timezone]),
        ),
    ]
