# Generated by Django 2.1.15 on 2020-01-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180704_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpolluser',
            name='auto_watch',
            field=models.BooleanField(default=False, help_text='Automatically watch polls you have voted in', verbose_name='Auto Watch Polls'),
        ),
        migrations.AlterField(
            model_name='bitpolluser',
            name='email_invitation',
            field=models.BooleanField(default=True, help_text='Send E-Mails for group and poll invitations', verbose_name='Email Invitations'),
        ),
    ]
