# Generated by Django 2.2.28 on 2022-05-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220129_1728'),
        ('base', '0007_auto_20200123_1123'),
    ]

    operations = [
    ]
