# Generated by Django 4.0.4 on 2022-05-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220129_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpolluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
