# Generated by Django 3.2.13 on 2022-05-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_bitpolluser_first_name'),
        ('base', '0008_merge_20220505_2358'),
    ]

    operations = [
    ]
