# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('last_invited', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='one_vote_per_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollinvitation',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
        migrations.AddField(
            model_name='pollinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pollinvitation',
            unique_together=set([('user', 'poll')]),
        ),
    ]
