# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20170309_1709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollinvitation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='pollinvitation',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollinvitation',
            name='user',
        ),
        migrations.DeleteModel(
            name='PollInvitation',
        ),
    ]
