# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 21:59
from __future__ import unicode_literals

from django.db import migrations, models
#import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20170309_1709'),
    ]

    operations = [

        migrations.AlterField(
            model_name='comment',
            name='text',
            # Disabled as it is no longer used, and django_markdown is no longer used @Nils 6.5.22
            #field=django_markdown.models.MarkdownField(),
            field=models.TextField(),
        ),
    ]