# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20170310_2259'),
        ('poll', '0003_auto_20170310_2102'),
    ]

    operations = [
    ]
