# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 10:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_merge_20170310_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicevalue',
            name='color',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[a-fA-F0-9]{6}$', message='Give an HTML color without the #')]),
        ),
    ]
