# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20170419_1407'),
        ('poll', '0007_auto_20170419_1121'),
    ]

    operations = [
    ]
