# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20170426_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='use_user_timezone',
            field=models.BooleanField(default=False),
        ),
    ]
