# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_poll_use_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='sorting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('universal', 'Universal'), ('datetime', 'Date-Time'), ('date', 'Date')], max_length=20),
        ),
    ]
