# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_auto_20171017_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='hide_participants',
            field=models.BooleanField(default=False),
        ),
    ]
