# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_poll_hide_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='one_vote_per_user',
            field=models.BooleanField(default=True),
        ),
    ]
