# Generated by Django 2.1.14 on 2019-11-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_auto_20171114_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allow_unauthenticated_vote_changes',
            field=models.BooleanField(default=False),
        ),
    ]
