# Generated by Django 2.1.15 on 2020-01-04 23:51

import bitpoll.base.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_poll_allow_unauthenticated_vote_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='send_mail',
        ),
        migrations.AlterField(
            model_name='poll',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='allow_unauthenticated_vote_changes',
            field=models.BooleanField(default=False, verbose_name='allow unauthenticated vote changes'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='anonymous_allowed',
            field=models.BooleanField(default=True, verbose_name='allow anonymous votes'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='owning group'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='hide_participants',
            field=models.BooleanField(default=False, verbose_name='hide participants'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='one_vote_per_user',
            field=models.BooleanField(default=True, verbose_name='one vote per user'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='public_listening',
            field=models.BooleanField(default=False, verbose_name='public listening'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='require_invitation',
            field=models.BooleanField(default=False, verbose_name='invitation required to vote'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='require_login',
            field=models.BooleanField(default=False, verbose_name='login required'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='show_invitations',
            field=models.BooleanField(default=True, verbose_name='show invitations as empty votes'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='show_results',
            field=models.CharField(choices=[('summary', 'Summary'), ('complete', 'Complete'), ('never', 'Never'), ('summary after vote', 'Summary after Vote'), ('complete after vote', 'Complete after Vote')], default='complete', help_text='Owners of this poll and administrators will always see all votes.', max_length=20, verbose_name='Show Results'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sorting',
            field=models.IntegerField(choices=[(0, 'Date'), (1, 'Name')], default=0, verbose_name='Sort results by'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='timezone_name',
            field=models.CharField(default='Europe/Berlin', max_length=40, validators=[bitpoll.base.validators.validate_timezone], verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='use_user_timezone',
            field=models.BooleanField(default=False, verbose_name='Translate all times to the users timezone'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owning user'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='vote_all',
            field=models.BooleanField(default=False, verbose_name='forbid empty choices'),
        ),
    ]
