# Generated by Django 2.2.24 on 2022-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_poll_allow_unauthenticated_vote_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='show_score_in_summary',
            field=models.BooleanField(default=False),
        ),
    ]
