# Generated by Django 2.1.15 on 2020-01-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_auto_20200105_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='You can use <a href="http://daringfireball.net/projects/markdown/" target="_blank">Markdown</a> syntax for formatting.'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, help_text='You can use <a href="http://daringfireball.net/projects/markdown/" target="_blank">Markdown</a> syntax for formatting.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Post as anonymous vote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True, help_text='You can use <a href="http://daringfireball.net/projects/markdown/" target="_blank">Markdown</a> syntax for formatting.'),
        ),
    ]
