# Generated by Django 2.2.28 on 2022-05-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_auto_20200105_1425'),
        ('poll', '0018_poll_show_score_in_summary'),
    ]

    operations = [
    ]
