# Generated by Django 5.0.1 on 2024-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_alter_choice_id_alter_choicevalue_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='allow_unauthenticated_vote_changes',
            field=models.BooleanField(default=True),
        ),
    ]
