# Generated by Django 3.2.13 on 2022-05-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_alter_choice_id_alter_choicevalue_id_and_more'),
        ('poll', '0020_merge_20220505_2358'),
    ]

    operations = [
    ]
